title: Structurizr
description: Documentation for the Structurizr tooling.
theme: just-the-docs
color_scheme: structurizr

url: https://docs.structurizr.com

logo: "/assets/images/structurizr-banner.png"
favicon_ico: "/assets/images/favicon.ico"

nav_external_links:
  - title: Open JSON data format
    url: https://github.com/structurizr/json
  - title: Examples
    url: https://github.com/structurizr/examples
  - title: C4 model
    url: https://c4model.com

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/structurizr/structurizr.github.io"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"
