title: Structurizr
description: Documentation for the Structurizr tooling.
theme: just-the-docs
color_scheme: structurizr

url: https://docs.structurizr.com

logo: "/assets/images/structurizr-logo.png"
favicon_ico: "/assets/images/favicon.ico"

nav_external_links:
  - title: C4 model
    url: https://c4model.com