title: Structurizr
description: Documentation for the Structurizr tooling.
theme: just-the-docs

url: https://structurizr.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
